### ISSUE TITLE
can't unzip latest examples

### ISSUE THREAD

**Issue by ajdevy** [weiyialanchen/MacInstallation#1]
$ unzip Examples.zip 
Archive:  Examples.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Examples.zip or
        Examples.zip.zip, and cannot find Examples.zip.ZIP, period.

**Comment by weiyialanchen** [comment]
Corrected the command to download Examples.zip on the installation guide page

`curl -O https://raw.githubusercontent.com/weiyialanchen/MacInstallation/master/Examples.zip`
